export const listOfCountries = [
	'Abkhazia Georgia ',
	'Afghanistan ',
	'Albania ',
	'Algeria ',
	'American Samoa ',
	'Andorra ',
	'Angola ',
	'Anguilla ',
	'Antarctica ',
	'Antigua Barbuda ',
	'Argentina ',
	'Armenia ',
	'Aruba ',
	'Australia ',
	'Austria ',
	'Azerbaijan ',
	'Bahamas ',
	'Bahrain ',
	'Bangladesh ',
	'Barbados ',
	'Belarus ',
	'Belgium ',
	'Belize ',
	'Benin ',
	'Bermuda ',
	'Bhutan ',
	'Bolivia ',
	'Bonaire St Eustatius and Saba ',
	'Bosnia and Herzegovina ',
	'Botswana ',
	'Brazil ',
	'British Virgin Islands ',
	'Brunei ',
	'Bulgaria ',
	'Burundi ',
	'Cambodia ',
	'Cameroon ',
	'Canada ',
	'Cape Verde ',
	'Cayman Islands ',
	'Central Africa Republic ',
	'Chile ',
	'China ',
	'Cocos K I ',
	'Colombia ',
	'Comoros ',
	'Congo ',
	'Cook Islands ',
	'Costa Rica ',
	'Crimea ',
	'Croatia ',
	'Cura ao ',
	'Cyprus ',
	'Czech Republic ',
	'Democratic Republic of the Congo ',
	'Denmark ',
	'Djibouti ',
	'Dominica ',
	'Dominican Republic ',
	'East Timor ',
	'Ecuador ',
	'Egypt ',
	'El Salvador ',
	'Equatorial Guinea ',
	'Eritrea ',
	'Estonia ',
	'Ethiopia ',
	'Falkland Islands Malvinas ',
	'Faroe Islands ',
	'Fiji ',
	'Finland ',
	'France ',
	'French Guiana ',
	'French Polynesia ',
	'Gabon ',
	'Gambia ',
	'Georgia ',
	'Germany ',
	'Ghana ',
	'Gibraltar ',
	'Greece ',
	'Grenada ',
	'Guadeloupe ',
	'Guam ',
	'Guatemala ',
	'Guernsey ',
	'Guinea ',
	'Guyana ',
	'Haiti ',
	'Honduras ',
	'Hong Kong ',
	'Hungary ',
	'Iceland ',
	'India ',
	'Indonesia ',
	'Iran ',
	'Iraq ',
	'Ireland ',
	'Isle of Man ',
	'Israel ',
	'Italy ',
	'Ivory Coast ',
	'Jamaica ',
	'Japan ',
	'Jersey ',
	'Jordan ',
	'Kazakhstan ',
	'Kenya ',
	'Kiribati ',
	'Kosovo ',
	'Kuwait ',
	'Kyrgyzstan ',
	'Laos ',
	'Latvia ',
	'Lebanon ',
	'Lesotho ',
	'Liberia ',
	'Libya ',
	'Liechtenstein ',
	'Lithuania ',
	'Luxembourg ',
	'Macau ',
	'Macedonia ',
	'Madagascar ',
	'Malawi ',
	'Malaysia ',
	'Maldives ',
	'Mali ',
	'Malta ',
	'Martinique ',
	'Mauritania ',
	'Mauritius ',
	'Mexico ',
	'Moldova ',
	'Monaco ',
	'Mongolia ',
	'Montenegro ',
	'Montserrat ',
	'Morocco ',
	'Mozambique ',
	'Myanmar ',
	'Namibia ',
	'Nepal ',
	'Netherlands ',
	'New Caledonia ',
	'New Zealand ',
	'Nicaragua ',
	'Niger ',
	'Nigeria ',
	'Northern Mariana Islands ',
	'Norway ',
	'Oman ',
	'Pakistan ',
	'Palau ',
	'Palestinian Territory ',
	'Panama ',
	'Papua New Guinea ',
	'Paraguay ',
	'Peru ',
	'Philippines ',
	'Poland ',
	'Portugal ',
	'Puerto Rico ',
	'Qatar ',
	'Reunion ',
	'Romania ',
	'Russia ',
	'Rwanda ',
	'Saint Barts ',
	'Saint Kitts and Nevis ',
	'Saint Lucia ',
	'Saint Martin ',
	'Saint Vincent Grenadines ',
	'Samoa ',
	'San Marino ',
	'Saudi Arabia ',
	'Senegal ',
	'Serbia ',
	'Seychelles ',
	'Sierra Leone ',
	'Singapore ',
	'Slovakia ',
	'Slovenia ',
	'Somalia ',
	'South Africa ',
	'South Korea ',
	'South Sudan ',
	'Spain ',
	'Sri Lanka ',
	'St Maarten ',
	'St Pierre and Miquelon ',
	'Sudan ',
	'Suriname ',
	'Svalbard Jan Mayen ',
	'Swaziland ',
	'Sweden ',
	'Switzerland ',
	'Syria ',
	'Taiwan ',
	'Tajikistan ',
	'Tanzania ',
	'Thailand ',
	'Togo ',
	'Trinidad and Tobago ',
	'Tunisia ',
	'Turkey ',
	'Turkmenistan ',
	'Turks Caicos Islands ',
	'Tuvalu ',
	'U S Virgin Islands ',
	'Uganda ',
	'Ukraine ',
	'United Arab Emirates ',
	'United Kingdom ',
	'United States Minor Outlying Islands ',
	'United States of America ',
	'Uruguay ',
	'Uzbekistan ',
	'Vanuatu ',
	'Vatican City ',
	'Venezuela ',
	'Vietnam ',
	'Wallis and Futuna ',
	'Yemen ',
	'Zambia ',
	'Zimbabwe'
];
