# Generated by Django 3.2.12 on 2022-03-12 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hotel_history',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=100)),
                ('categories', models.CharField(blank=True, max_length=100, null=True)),
                ('hotel_rating', models.IntegerField(blank=True, null=True)),
            ],
        ),
    ]
